# Site settings
title: He Jiang's Personal Website
email: hejiang@pku.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  I am currently a full-time research assistant at HKUST.
  I'm applying for PhD positions in machine learning and natural
  language processing. My research interest lies in the spectrum
  of machine learning, especially for interesting models and
  algorithms in 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hejiang.space" # the base hostname & protocol for your site
twitter_username: ChiqutaBomb
github_username:  DeiPlusAY

# Build settings
markdown: kramdown
